// apps/web/src/lib/utils/pdf.ts
import "server-only"

import { createElement } from "react"
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer"

export type EfirPdfInput = {
  draftId: string
  incidentId: string
  stationName: string
  touristName: string | null
  nationality: string | null
  occurredAt: string
  zoneName: string | null
  addressText: string | null
  lat: number | null
  lon: number | null
  incidentType: string
  severity: string
  narrative: string
}

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111",
  },
  banner: {
    backgroundColor: "#7c2d12",
    color: "#fff",
    padding: 8,
    marginBottom: 12,
    fontSize: 9,
    textAlign: "center",
  },
  title: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    marginBottom: 12,
  },
  row: { marginBottom: 4 },
  label: { fontFamily: "Helvetica-Bold" },
  narrative: {
    marginTop: 12,
    lineHeight: 1.4,
    whiteSpace: "pre-wrap",
  },
  footer: {
    marginTop: 24,
    fontSize: 8,
    color: "#444",
  },
})

function EfirDocument(props: EfirPdfInput) {
  return createElement(
    Document,
    { title: `E-FIR draft ${props.draftId}` },
    createElement(
      Page,
      { size: "A4", style: styles.page },
      createElement(
        View,
        { style: styles.banner },
        createElement(
          Text,
          null,
          "DRAFT E-FIR — NOT A FILED FIR. Every [OFFICER TO VERIFY] marker must be confirmed before submission.",
        ),
      ),
      createElement(Text, { style: styles.title }, "First Information Report (Draft)"),
      createElement(
        Text,
        { style: styles.subtitle },
        `${props.stationName} · Ministry of Development of North Eastern Region`,
      ),
      createElement(
        Text,
        { style: styles.row },
        createElement(Text, { style: styles.label }, "Draft ID: "),
        props.draftId,
      ),
      createElement(
        Text,
        { style: styles.row },
        createElement(Text, { style: styles.label }, "Incident ID: "),
        props.incidentId,
      ),
      createElement(
        Text,
        { style: styles.row },
        createElement(Text, { style: styles.label }, "Subject: "),
        `${props.touristName ?? "[OFFICER TO VERIFY]"} (${props.nationality ?? "[OFFICER TO VERIFY]"})`,
      ),
      createElement(
        Text,
        { style: styles.row },
        createElement(Text, { style: styles.label }, "Occurrence: "),
        `${props.incidentType.replaceAll("_", " ")} · ${props.severity} · ${props.occurredAt}`,
      ),
      createElement(
        Text,
        { style: styles.row },
        createElement(Text, { style: styles.label }, "Place: "),
        `${props.zoneName ?? "[OFFICER TO VERIFY]"} / ${props.addressText ?? "[OFFICER TO VERIFY]"} (${props.lat ?? "?"}, ${props.lon ?? "?"})`,
      ),
      createElement(Text, { style: styles.narrative }, props.narrative),
      createElement(
        Text,
        { style: styles.footer },
        "Generated by the Smart Tourist Safety system. The LLM only formats the structured record; it does not decide whether an alert fires. SHA-256 of this PDF is queued for on-chain anchoring (keccak256 commitment, no PII).",
      ),
    ),
  )
}

export async function renderEfirPdf(input: EfirPdfInput): Promise<Buffer> {
  const buffer = await renderToBuffer(EfirDocument(input))
  return Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer)
}
