// apps/web/src/lib/chain/abi/IncidentAnchor.ts
// Generated by tools/scripts/copy-abi.sh — do not edit by hand.

export const incidentAnchorAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ANCHOR_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "anchor",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "touristToken",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "kind",
        "type": "uint8",
        "internalType": "enum IncidentAnchor.AnchorKind"
      },
      {
        "name": "severity",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "occurredAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "sequence",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "anchorBatch",
    "inputs": [
      {
        "name": "incidentIds",
        "type": "bytes16[]",
        "internalType": "bytes16[]"
      },
      {
        "name": "recordHashes",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      },
      {
        "name": "touristTokens",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "kinds",
        "type": "uint8[]",
        "internalType": "enum IncidentAnchor.AnchorKind[]"
      },
      {
        "name": "severities",
        "type": "uint8[]",
        "internalType": "uint8[]"
      },
      {
        "name": "occurredAts",
        "type": "uint64[]",
        "internalType": "uint64[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "anchorCount",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "anchorsOf",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct IncidentAnchor.Anchor[]",
        "components": [
          {
            "name": "recordHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "touristToken",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "occurredAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "anchoredAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "enum IncidentAnchor.AnchorKind"
          },
          {
            "name": "severity",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestAnchor",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IncidentAnchor.Anchor",
        "components": [
          {
            "name": "recordHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "touristToken",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "occurredAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "anchoredAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "enum IncidentAnchor.AnchorKind"
          },
          {
            "name": "severity",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalAnchors",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyIntegrity",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "matched",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "anchoredAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Anchored",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "touristToken",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": true,
        "internalType": "enum IncidentAnchor.AnchorKind"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "severity",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "occurredAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "anchoredAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "sequence",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessControlBadConfirmation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "neededRole",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyHash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAnchored",
    "inputs": [
      {
        "name": "incidentId",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ]
  }
] as const;
